#!/usr/bin/env node
var LinkedDataFragmentsClient = require('./lib/LinkedDataFragmentsClient'),
    client = new LinkedDataFragmentsClient('http://localhost:3000/dbpedia');

client.getQueryResults(
    'SELECT ?p WHERE {' +
    '?b a <http://dbpedia.org/ontology/Country>. ' +
    '?b <http://dbpedia.org/property/commonName> "Belgium"@en. ' +
    '?p a <http://dbpedia.org/ontology/Person>. ' +
    '?p <http://dbpedia.org/ontology/birthPlace> ?c. ' +
    '?c <http://dbpedia.org/property/name> "Ghent"@en. }')
  .then(console.log, console.log);
