SELECT ?person WHERE {
	?person a dbpedia-owl:Artist;
	        dbpedia-owl:birthPlace ?city.
	?city dbpprop:name ?name;
	      dbpedia-owl:country ?country.
	?country dbpprop:commonName "Belgium"@en.
}
