SELECT ?person, ?name WHERE {
  ?person a dbpedia-owl:Artist;
          dbpprop:name ?name;
          dbpedia-owl:birthPlace ?city.
  ?city dbpprop:name ?cityName;
        dbpprop:name "Hasselt"@en;
        dbpedia-owl:country ?country.
  ?country dbpprop:commonName "Belgium"@en.
}
