CONSTRUCT {
  ?person a dbpedia-owl:Artist;
          rdfs:label ?name;
          dbpedia-owl:birthPlace ?city.
}
WHERE {
  ?person a dbpedia-owl:Artist;
          rdfs:label ?name;
          dbpedia-owl:birthPlace ?city.
  ?city rdfs:label "Ghent"@en.
  FILTER LANGMATCHES(LANG(?name), "EN")
}
