SELECT ?p WHERE {
    ?p a <http://dbpedia.org/ontology/Artist>;
       <http://dbpedia.org/ontology/birthPlace> [
         <http://xmlns.com/foaf/0.1/name> "York"@en;
         <http://www.w3.org/2000/01/rdf-schema#label> _:label
       ]
}
