SELECT $drug $keggUrl $chebiImage WHERE {
   $drug <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://www4.wiwiss.fu-berlin.de/drugbank/resource/drugbank/drugs> .
   $drug <http://www4.wiwiss.fu-berlin.de/drugbank/resource/drugbank/keggCompoundId> $keggDrug .
   $keggDrug <http://bio2rdf.org/ns/bio2rdf#url> $keggUrl .
   $drug <http://www4.wiwiss.fu-berlin.de/drugbank/resource/drugbank/genericName> $drugBankName .
   $chebiDrug <http://purl.org/dc/elements/1.1/title> $drugBankName .
   $chebiDrug <http://bio2rdf.org/ns/bio2rdf#image> $chebiImage .
}
