#!/usr/bin/env node
/*! @license ©2014 Ruben Verborgh - Multimedia Lab / iMinds / Ghent University */

var fragmentUrl = 'http://data.linkeddatafragments.org/dbpedia{?subject,predicate,object}';

var FragmentsClient = require('../../lib/http/FragmentsClient'),
    UriTemplate = require('uritemplate'),
    SingleItemIterator = require('../../lib/iterators/SingleItemIterator'),
    TriplePatternIterator = require('../../lib/iterators/TriplePatternIterator'),
    rdf = require('../../lib/rdf/RdfUtil');

var client = new FragmentsClient(UriTemplate.parse(fragmentUrl)),
    iteratorOptions = { fragmentsClient: client };

var p_type_artist = rdf.triple('?p', rdf.RDF_TYPE, rdf.DBPEDIAOWL + 'Artist'),
    p_birthPlace_c = rdf.triple('?p', rdf.DBPEDIAOWL + 'birthPlace', '?c'),
    c_name_York = rdf.triple('?c', rdf.FOAF + 'name', '"York"@en');

var bindingsStream =
  new SingleItemIterator({ })
  .pipe(new TriplePatternIterator(c_name_York, iteratorOptions))
  .pipe(new TriplePatternIterator(p_birthPlace_c, iteratorOptions))
  .pipe(new TriplePatternIterator(p_type_artist, iteratorOptions));

bindingsStream.on('data', function (bindingsContext) {
  console.log(JSON.stringify(bindingsContext.bindings));
});
bindingsStream.on('error', console.error);
