SELECT ?film ?director ?genre WHERE {
?film <http://dbpedia.org/ontology/director>  ?director .
?director <http://dbpedia.org/ontology/nationality> <http://dbpedia.org/resource/Italy> .
?x <http://www.w3.org/2002/07/owl#sameAs> ?film .
?x <http://data.linkedmdb.org/resource/movie/genre> ?genre .
}
